name: Playwright Tests with MetaMask

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Download MetaMask Extension
      run: |
        mkdir metamask
        curl -L -o metamask.zip https://github.com/MetaMask/metamask-extension/releases/download/12.6.0/metamask-chrome-12.0.6.zip
        unzip metamask.zip -d metamask

    - name: Run tests with Playwright
      run: |
        npx playwright install
        npx playwright test ./Tests/example.spec.js --headed
      env:
        METAMASK_PATH: ${{ github.workspace }}/metamask
