name: Playwright Tests with MetaMask

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.17.0

    - name: Install Dependencies
      run: |
          npm install
          npx playwright install chromium
    - name: Install Xvfb
      run: |
          sudo apt-get update
          sudo apt-get install xvfb

    - name: Set up Xvfb
      run: |
          Xvfb :99 &
          export DISPLAY=:99
      
    - name: Download MetaMask Extension
      run: |
        mkdir metamask
        curl -L -o metamask.zip https://github.com/MetaMask/metamask-extension/releases/download/v12.6.0/metamask-chrome-v12.6.0.zip
        powershell -Command "Expand-Archive -Path metamask.zip -DestinationPath metamask"
      
    - name: Run tests with Playwright
      run: |
        npx playwright test ./Tests/example.spec.js --headed
      env:
        METAMASK_PATH: ${{ github.workspace }}/metamask
        DISPLAY: :99
