name: Playwright Tests with MetaMask

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.17.0

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Download and Unzip MetaMask Extension
      run: |
        mkdir metamask
        curl -L -o metamask.zip https://github.com/MetaMask/metamask-extension/releases/download/v12.6.0/metamask-chrome-v12.6.0.zip
        powershell -Command @"
          try {
            Add-Type -AssemblyName 'System.IO.Compression.FileSystem'
            [System.IO.Compression.ZipFile]::ExtractToDirectory('metamask.zip', 'metamask')
          } catch {
            Write-Host 'ZIP extraction failed, attempting alternate method'
            Expand-Archive -Path 'metamask.zip' -DestinationPath 'metamask'
          }
        "@

    - name: Run tests with Playwright
      run: |
        npx playwright test ./Tests/example.spec.js --headed
      env:
        METAMASK_PATH: ${{ github.workspace }}/metamask
